apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greet-server.fullname" . }}
  labels:
    {{- include "greet-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "greet-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "greet-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.grpcServerPort | default .Values.service.port }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRPC_PORT
              value: {{ .Values.grpcServerPort | default .Values.service.port | quote }}
            - name: GRPC_HOST
              value: "0.0.0.0"
