apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greet-client.fullname" . }}
  labels:
    {{- include "greet-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "greet-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "greet-client.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageRegistry | default .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort | default .Values.service.port }}
          env:
            - name: ASPNETCORE_URLS
              value: http://+:{{ .Values.containerPort | default .Values.service.port }}
            - name: GrpcGreetServerUrl
              value: {{ tpl .Values.GrpcGreetServerUrl . | quote }}
            {{- if eq (include "greet-client.name" .) "cslb-greet-client" }}
            - name: GprcGreetServerHost1
              value: {{ .Release.Name }}-cslb-greet-server1
            - name: GprcGreetServerPort1
              value: "50052"
            - name: GprcGreetServerHost2
              value: {{ .Release.Name }}-cslb-greet-server2
            - name: GprcGreetServerPort2
              value: "50053" 
            {{- end }}