services:
  greet-server:
    container_name: greet.server
    image: greet/server
    build: 
      context: .
      dockerfile: Dockerfile.GreetServer
      target: development
    ports:
      - 50051:5001
    develop:
      watch:
        - action: rebuild
          path: ./GreetServer/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=5001

  greet-client:
    container_name: greet.client
    image: greet/client
    build: 
      context: .
      dockerfile: Dockerfile.GreetClient
      target: development
    ports:
      - 80:8081
    depends_on:
      - greet-server
    develop:
      watch:
        - action: rebuild
          path: ./GreetClient/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8081
      - GrpcGreetServerUrl=http://host.docker.internal:50051